### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by cluzier** [woomyware/woomy#22]
Once cloned, when I go to install the dependencies with ether `npm i` or `npm install`, it gives me this error:
```
npm ERR! Cannot read property 'matches' of undefined
```

I have googled to find a fix but all results are saying to delete the package-lock.json file and node_modules folder. I do not have these in my directory so I am stuck. Not sure if anyone else has experienced this before.

**Comment by mudkipscience** [comment]
Weird, I just installed the dependencies fine on my machine (x86_64, Ubuntu 20.10)

Do you have any further details? SQLite has known to have caused issues in the past.

**Comment by mudkipscience** [comment]
I don't think this is related to Woomy given that I've been unable to re-produce this on either Ubuntu or Windows 10, im suspecting something wrong on your machine

Few things you can try:
- running `npm cache clear -- force`
- deleting package-lock.json and node_modules directory (although you said you've already done that)
- make sure you have build tools installed (this causes the SQLite issue mentioned above, if they are missing)
